"use client"

import { useEffect } from "react"
import { useToast } from "@/hooks/use-toast"
import type { Alert } from "@/lib/types"

const POLL_INTERVAL_MS = 15000
const ALERT_FETCH_LIMIT = 50

type AlertToastPayload = Pick<
  Alert,
  "id" | "createdAt" | "hazardType" | "severity" | "description" | "reason" | "status"
>

const FALLBACK_ALERT: AlertToastPayload = {
  id: "test-alert",
  createdAt: new Date(),
  hazardType: "unknown",
  description: "Test alert generated by polling.",
  reason: "Synthetic alert",
  severity: "warn",
  status: "open",
}

export function AlertToastListener() {
  const { toast } = useToast()
  useEffect(() => {
    let isActive = true

    const fetchAlerts = async () => {
      try {
        const response = await fetch(`/api/alerts?status=open&limit=${ALERT_FETCH_LIMIT}`)
        if (!response.ok) return
        const data = await response.json()
        if (!isActive) return
        const alerts = (data.alerts ?? []) as Alert[]
        const alert =
          alerts.length > 0
            ? (alerts[Math.floor(Math.random() * alerts.length)] as AlertToastPayload)
            : { ...FALLBACK_ALERT, id: `test-alert-${Date.now()}`, createdAt: new Date() }

        toast({
          title: `Alert: ${alert.hazardType.replace(/_/g, " ")}`,
          description: alert.description,
          variant: alert.severity === "critical" ? "destructive" : "default",
        })

        if (typeof window !== "undefined") {
          window.dispatchEvent(new CustomEvent("alert.toast", { detail: alert }))
        }
      } catch (error) {
        console.error(error)
      }
    }

    fetchAlerts()
    const interval = setInterval(fetchAlerts, POLL_INTERVAL_MS)

    return () => {
      isActive = false
      clearInterval(interval)
    }
  }, [toast])

  return null
}
